# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coveralls coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Run headless tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm run test-coverage
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.0
      env:
        NODE_COVERALLS_DEBUG: 1
      with:
        path-to-lcov: ./coverage/lcov/lcov.info
        github-token: ${{ secrets.github_token }}
